### ISSUE TITLE
How to getText() from an element using Java?

### ISSUE THREAD

**Issue by rafaelcarmos** [2gis/Winium.Desktop#144]
When I call getText() upon an element I'm getting the following message:

`NO GET TEXT (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 16 milliseconds Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700' System info: host: 'd-1816', ip: '10.10.25.26', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0' Driver info: org.openqa.selenium.winium.WiniumDriver Capabilities [{app=C:\Windows\system32\calc.exe, args=, innerPort=9998, debugConnectToRunningApp=false, keyboardSimulator=1, launchDelay=0, platform=ANY}] Session ID: AwesomeSession`

Is there a way of getting an elements text with Winium?

**Comment by mikeliucc** [comment]
Not every element has the "text" attribute.  Maybe its "label" you are looking for?

Some code snippet of what you are trying to do might help..

**Comment by rafaelcarmos** [comment]
I'm using Selenium Webdriver in a custom testing framework I'm developing. And we were interested in Winium to provide the automation of Windows applications.

My first test with Winium in Java was with a simple script to automate the Windows calculator app.
I mapped out the element that holds the operations result, and was trying to assert the shown value. Just like this:

```
int expectedResult = 8; 
Element element = driver.findElement(By.id("150")); //element was found just fine
String result = element.getText(); // in this line I get the "NO GET TEXT" warning
int numericResult = Integer.parseInt(result);
Assert.assertEquals(expectedResult, numericResult);
```

Apparently the Webdriver getText() method is not yet implemented for the Winium Java bindings. I also tried to extract the text from the element using the CommandExecutor, didn't succeed though.

**Comment by OtherVibes** [comment]
I've just migrated from Python to Java and the `getText()` method works for me.
I'm not sure what `Element` is (in your second line). I'm using `WebElement` type, try to use it instead and let us know if it still throws exception.

**Comment by NickAb** [comment]
`getText` should work independently of bindings language you chose to use.

In case of windows calc.exe you should use `Name` property on the result element, not `getText`.

Here is sample in python
```py
window.find_element_by_id('150').get_attribute('Name')
```

Please make sure that the element itself has a text value. If some child of found element has the text, no the element you located, then try get this child element first and call `getText` on the child.

Internally Winium tries to use TextPattern first, then ValuePattern to get text of the element. If the element does not support those automation patterns (i.e. it is some custom element that does not implement patterns), then the method will fail.

**Comment by ShreyasPatil** [comment]
Thanks worked for me as well. Following is Ruby sample code
`ele = driver.find_element(:id, "65535").attribute('Name')`

**Comment by smrabhi** [comment]
@rafanukem : How did you solve your problem.I am facing the same problem ."getAttribute " is not working for me.
GetText is giving warning.

I want to get the value of the text filled in the box which is 8201_PIP_100_101

@NickAb : Please help

![image](https://user-images.githubusercontent.com/11434692/38402773-d7bcd074-39b2-11e8-9efd-0c2d9533cc6d.png)

**Comment by joshidipakkumar** [comment]
Applicable to java as well. I used it for to get a label displayed on a Button.
driver.findElement(By.id("id")).getAttribute("name");
